environment:
  DNX_BUILD_VERSION: build%APPVEYOR_BUILD_NUMBER%

assembly_info:
  patch: false

before_build:
  - dotnet restore

build_script:
  - dotnet --version
  - cmd: dotnet_gitversion_project.cmd .\src\AppSyndication.UserService.Web  publish -o %APPVEYOR_BUILD_FOLDER%\artifacts\web -c Release
  - cmd: dotnet_gitversion_project.cmd .\src\AppSyndication.UserService.Model pack -o %APPVEYOR_BUILD_FOLDER%\artifacts\nuget -c Release

artifacts:
  - path: artifacts\web\
    name: web-artifacts

deploy:
  - provider: WebDeploy
    server: https://as-usr.scm.azurewebsites.net:443/msdeploy.axd?site=as-usr
    website: as-usr
    username: $as-usr
    password:
      secure: qyPdxs1aPgWHVs8Hjv5bY7B0mugJamsXV+yaYyENDMHMnO2zImVHnSvGVx6VvMVLtC8KVETxjxl0CvtBNxG6xw==
    remove_files: true
    app_offline: true
    artifact: web-artifacts
