- # Master build and deploy.
  branches:
    only:
      - master

  version: 0.0.1-build-{build}

  configuration: Release

  environment:
    DNX_BUILD_VERSION: build-%APPVEYOR_BUILD_NUMBER%
    GITHUB_ACCESS_TOKEN:
      secure: DcAkF5ZAi8KAtzqJRXwWm6GAXrvkpF8Wd2M5I4O3TYPrdRpyoZIhh/ZnFJgITlEC

  before_build:
    - dotnet restore

  build_script:
    - appveyor.cmd

  artifacts:
    - path: artifacts\nuget\
    - path: artifacts\web\
      name: web-artifacts

  nuget:
    account_feed: true
    project_feed: true

  deploy:
    - provider: WebDeploy
      server: https://as-usr.scm.azurewebsites.net:443/msdeploy.axd?site=as-usr
      website: as-usr
      username: $as-usr
      password:
        secure: qyPdxs1aPgWHVs8Hjv5bY7B0mugJamsXV+yaYyENDMHMnO2zImVHnSvGVx6VvMVLtC8KVETxjxl0CvtBNxG6xw==
      remove_files: true
      app_offline: true
      artifact: web-artifacts

  on_success:
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_ACCESS_TOKEN):x-oauth-basic@github.com`n"
    - git config --global user.email "a@appsyndication.com"
    - git config --global user.name "Apps-Bot"
    - git tag -a v%APPVEYOR_BUILD_VERSION% -m "Build v%APPVEYOR_BUILD_VERSION%"
    - git push --tags origin HEAD:master

  skip_tags: true

- # Development branches build.
  version: 0.0.1-build-{branch}-{build}

  configuration: Debug

  environment:
    DNX_BUILD_VERSION: build-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_NUMBER%

  before_build:
    - dotnet restore

  build_script:
    - appveyor.cmd

  nuget:
    account_feed: true
    project_feed: true

  skip_tags: true
