install:
  - choco install gitversion.portable -pre -y

environment:
  DNX_BUILD_VERSION: build%APPVEYOR_BUILD_NUMBER%

assembly_info:
  patch: false

before_build:
  - dotnet restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - dotnet --version
  - cmd: dotnet publish .\src\AppSyndication.UserService.Web -o %APPVEYOR_BUILD_FOLDER%\artifacts\web -c Release
  - cmd: dotnet pack .\src\AppSyndication.UserService.Model -o %APPVEYOR_BUILD_FOLDER%\artifacts\nuget -c Release

artifacts:
  - path: artifacts\web\
    name: web-artifacts

deploy:
  - provider: WebDeploy
    server: https://as-usr.scm.azurewebsites.net:443/msdeploy.axd?site=as-usr
    website: as-usr
    username: $as-usr
    password:
      secure: qyPdxs1aPgWHVs8Hjv5bY7B0mugJamsXV+yaYyENDMHMnO2zImVHnSvGVx6VvMVLtC8KVETxjxl0CvtBNxG6xw==
    remove_files: true
    app_offline: true
    artifact: web-artifacts
